CREATE TABLE `TB_RANDOM_MONEY_RECEIVE_INFO` (
  `META_INFO_SEQ` int(11) NOT NULL,
  `DIST_SEQ` int(11) NOT NULL,
  `RECEIVER_ID` varchar(45) COLLATE latin1_general_ci NOT NULL,
  `AMOUNT` int(11) NOT NULL,
  `CRETE_DATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `META_SEQ_RECEIVER_ID` (`META_INFO_SEQ`,`RECEIVER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
